### ISSUE TITLE
Hamelin-net produces an error when receiving an EOF

### ISSUE THREAD

**Issue by zippynk** [Hardmath123/hamelin#6]
`Exception in thread server-thread-[grep]:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/Macbook_2/Downloads/hamelin-master 5/hamelin-py/bin/hamelin.py", line 90, in event_loop
    self.handle_quit(poll)
  File "/Users/Macbook_2/Downloads/hamelin-master 5/hamelin-py/bin/hamelin-net", line 39, in quit
    conn.shutdown(socket.SHUT_RDWR)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 57] Socket is not connected`

Latest from master as of this posting with Python 2.7.8 (v2.7.8:ee879c0ffa11, Jun 29 2014, 21:07:35) and  I don't know what version of netcat on Mac OS 10.10 Yosemite. 

Hamelin continues to work fine after displaying the error message, and it doesn't stop the program from running.

**Comment by zippynk** [comment]
Fixed (if little hackily) so that it prints a custom error message in zippynk/patch-1.
